### ISSUE TITLE
Instantly closes when dragging/dropping a file.

### ISSUE THREAD

**Issue by illuZion9999** [ZrCulillo/JIT-Freezer#1]
Hello,
First I wanted to thank you for this tool, that is definitively useful and I really appreciate it!
Even though it worked on several files, it instantly closed when I dragged/dropped one, without displaying any error.
I attached the file so you can check what is wrong.
illuZion.
[File that doesn't work.zip](https://github.com/ZrCulillo/JIT-Freezer/files/4503367/File.that.doesn.t.work.zip)

**Comment by ZrCulillo** [comment]
Hey! I didn't find any problem, all worked fine for me. If it keeps happening to you, don't hesitate to reopen the issue. By the way, I've attached the file without the native layer.


Download: [.NET File](https://github.com/ZrCulillo/JIT-Freezer/files/4503553/default.NET.File.zip)

**Comment by LegitSoulja** [comment]
Works fine? xD, do you even know how to program, maybe but not efficiently it's horrible!

Anyhow, I discovered this project and was wondering what it was but just a useless console application. Just by looking at your code, and this issue this never worked fine. After drag/dropping a file into console, after read line the application will just close as you have a return statement afterwards. Return would not execute the code below out of the function scope!.

**Comment by ZrCulillo** [comment]
What constructive criticism! "Your code is horrible but I won't tell you why because I don't know either."

- Do you even know what this program is for?
- The problem of the previous user who commented, was not the fault of the program, it was the fault of him who was using it wrong and it was fixed on Discord.
- I use it constantly and quite a few people I know too, so, yes! It works fine, maybe, you just don't know how to use a simple program like the one in front of you.
